In [7]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.datasets import load_boston
df= load_boston()

df.keys()

print(df.data)
boston=pd.DataFrame(df.data, columns=df.feature_names)
boston.head()
boston["MVDV"]=df.target
boston.head()
boston.isnull().sum()

from sklearn.model_selection import train_test_split
x=boston.drop("MVDV", axis=1)
y=boston["MVDV"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_states=5)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

frpm sklearn.linear_model import LinearRegression
from sklearn.metrices importmean_square_error

lin_model=LinearRegression()
lin_model.fit(x_train,y_train)
Y_train.predict=lin_model.predict(x_train)
rmse=(np,sqrt(mean_squared_erro(y_train,Y_train_predict)))

print("the model performance for training set")
print("RMSE is {}."format(rmse))
print("/n")
Y_test.predict=lin_model.predict(x_test)
rmse=(np,sqrt(mean_squared_erro(y_test,Y_test_predict)))

print("the model performance for testing set")
print("RMSE is {}."format(rmse))+


[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

TypeError: ignored